# folders
alias cdp='cd ${HOME}/projects; clas;'
alias cpd='cdp'
alias cdd='cd ${HOME}/Downloads; clas;'
alias cds='cd ${HOME}/Desktop/'
alias cdss='cd ${HOME}/scripts/; clas'
alias cdds='cdss'
alias cdu='cd $HOME}; clas;'
alias las='ls -las'
alias lasc='clear; ls -las'
alias clas='clear; printf "\nContents of: `pwd`\n\n"; ls -las'
alias cbd='cdb'
alias cd..='cd ..'
alias cdscr='cd ~/scripts; pwd; code .'
# end folders
